version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 1433:5432

    environment:
      - POSTGRES_DB=Akademine
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dominix125

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080